### ISSUE TITLE
Fix footer to the bottm

### ISSUE THREAD

**Issue by Wyfy0107** [Integrify-Team-4/Tindev-Frontend#45]
Currently the footer is moving with scroll, it needs to be fixed to the bottom

**Comment by Nejo12** [comment]
<img width="1387" alt="Screenshot 2020-12-29 at 23 18 10" src="https://user-images.githubusercontent.com/42632188/103317669-284bba00-4a2c-11eb-8ef8-5321d381faee.png">


Footer fixed to bottom
